' java.exe -jar C:\Apps\bin\plantuml.jar .\docs\console_ui.puml
@startuml
class ConsoleUi {
    - AppConfiguration _config
    - SeatStatus _seat_status
    -- Constants --
    - int MAX_ROWS = 26
    - int MAX_SEATS_PER_ROW = 50
    -- Methods --
    + __init__(config: AppConfiguration, seat_status: Optional[SeatStatus] = None)
    + prompt_for_application_start_details() : Tuple[str, int, int] | None
    + display_menu(seating_plan: SeatingPlan) : int
    + prompt_for_number_of_seats_to_book(seating_plan: SeatingPlan) : Optional[int]
    + display_seating_map(seating_plan: SeatingPlan) : None
    + prompt_for_booking_confirmation() : str
    + prompt_for_booking_id() : str
    + display_exit_message() : None
}

class AppConfiguration
class SeatStatus
class SeatingPlan
class Seat

ConsoleUi --> AppConfiguration
ConsoleUi --> SeatStatus
ConsoleUi --> SeatingPlan
SeatingPlan --> "*" Seat

@enduml
