' java.exe -jar C:\Apps\bin\plantuml.jar .\docs\shared_data_models.puml
@startuml
class AppConfiguration

class SeatStatus {
    AVAILABLE: str
    BOOKED: str
    PROPOSED: str
    +from_config(config: AppConfiguration): SeatStatus
}

class Seat {
    row: int
    col: int
    status: str
    +is_available(seat_status: SeatStatus): bool
}

class SeatingPlan {
    title: str
    plan: List<List<Seat>>
    available_seats_count: int
    booking_id: Optional[str]
    +get_available_seats(seat_status: SeatStatus): List<Seat>
}

SeatStatus --> AppConfiguration : Uses config
Seat --> SeatStatus : Uses statuses
SeatingPlan --> Seat : Contains multiple seats

@enduml
